import turtle
import lsystem
def main():
        t = turtle.Turtle()
        t.speed(0)
        wd = turtle.Screen()
        #uncomment the below line of code to make things run faster, but they won't display.
        #wd.tracer(0,0)
        print("Test # 1: The Arrowhead Curve\n######################################\n")
        sys = lsystem.LSystem("arrowheadcurve.txt")
        sys.createLSystem()
        sys.drawLSystem(t)
        t.clear()
        t.reset()
        print("Test # 2: The Hilbert Curve\n######################################\n")
        sys2 = lsystem.LSystem("hilbertcurve.txt")
        sys2.createLSystem()
        sys2.drawLSystem(t)
        t.clear()
        t.reset()
        print("Test # 3: The Dragon Curve\n######################################\n")
        sys3 = lsystem.LSystem("dragoncurve.txt")
        sys3.createLSystem()
        sys3.drawLSystem(t)
        t.clear()
        t.reset()
        print("Test # 4: The Peano-Gosper Curve\n######################################\n")
        sys4 = lsystem.LSystem("peanogospercurve.txt")
        sys4.createLSystem()
        sys4.drawLSystem(t)
        t.clear()
        t.reset()
        print("Test # 6: The Sierpinski Triangle Curve\n######################################\n")
        sys5 = lsystem.LSystem("sierpinskitrianglecurve.txt")
        sys5.createLSystem()
        sys5.drawLSystem(t)
        print("Test # 7: Handling File Not Found Error\n######################################\n")
        lsystem.LSystem("not_a_real_file.txt")
        wd.exitonclick()
main()
