def main():
    weeks_str = input("Please enter the number of weeks this semester:  ")
    print(weeks_str, "string")
    classes_str = input("Enter the number of classes you are taking:  ")
    print(classes_str, "string")
    classes_per_week_str = input("Enter the number of times per week your class meets:  ")
    print(classes_per_week_str, "string")
    tuition_str = input("Please enter your tuition:  ")
    print(tuition_str, "string")
    weeks = int(weeks_str)
    classes = int(classes_str)
    tuition = int(tuition_str)
    classes_per_week = int(classes_per_week_str)
    cost_per_week = ((tuition / classes) / weeks)
    cost_per_class = (cost_per_week / classes_per_week)
    print("Cost per week:", cost_per_week)
    print("Cost per class:", cost_per_class, "dollars, so don't skip class!")
main()
